default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff
        name: lint with ruff
        language: system
        entry: ruff check --force-exclude --fix --diff
        types: [python]
        require_serial: true

      - id: ruff-format
        name: format with ruff
        language: system
        entry: ruff format --force-exclude --diff
        types: [python]
        require_serial: true
