$schema": http://json-schema.org/draft-07/schema#
type: object
additionalProperties: false
properties:
  roles:  # Detailed validation is performed elsewhere
    description: The value is passed to BasicAPIAccessControl object
  users:
    oneOf:
      - type: object
        additionalProperties: false
        patternProperties:
          "^[0-9a-zA-Z_]+$":
            oneOf:
              - type: object
                additionalProperties: false
                properties:
                  roles:
                    oneOf:
                      - type: array
                        items:
                          type: string
                          pattern: "^[a-zA-Z_][0-9a-zA-Z_]*$"
                      - type: string
                        pattern: "^[a-zA-Z_][0-9a-zA-Z_]*$"
                      - type: "null"
                  displayed_name:
                    oneOf:
                      - type: string
                        pattern: "^.+$"
                      - type: "null"
                  mail:
                    oneOf:
                      - type: string
                        pattern: "^.+@.+$"
                      - type: "null"
              - type: "null"
      - type: "null"
