name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'bluesky'

    name: Build and publish docs

    runs-on: ubuntu-latest

    env:
      python_env: py313

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "7.x"

      - uses: prefix-dev/setup-pixi@v0.10.0

      - name: Install dev dependencies
        run: |
          set -vxeuo pipefail
          pixi install --environment=${{ env.python_env }}
          pixi run pip install --environment=${{ matrix.python-env }} "git+https://github.com/bluesky/bluesky-queueserver.git@main"
          pixi run pip install --environment=${{ matrix.python-env }} "git+https://github.com/bluesky/bluesky-queueserver-api.git@main"

          pixi list --environment=${{ env.python_env }}
          pixi run --environment=${{ env.python_env }} pip list
          pixi run --environment=${{ env.python_env }} conda list

      - name: Run pre-commit
        run: |
          pixi run --environment=${{ env.python_env }} make -C docs/ html

      - name: Deploy documentation to blueskyproject.io
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DOCUMENTATION_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./docs/build/html
          external_repository: bluesky/bluesky.github.io
          destination_dir: bluesky-httpserver
          keep_files: true  # Keep old files.
          force_orphan: false  # Keep git history.
