name: Check Code Style - ISORT

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          # These packages are installed in the base environment but may be older
          # versions. Explicitly upgrade them because they often create
          # installation problems if out of date.
          python -m pip install --upgrade pip setuptools numpy

          pip install isort
      - name: Run ISort
        run: |
          isort . -c
