name: Publish the release to PyPI

on:
  release:
    types: [created]

jobs:
  build:

    name: Upload to PyPI

    permissions:
      id-token: write

    if: github.repository_owner == 'bluesky'
    runs-on: ubuntu-latest

    env:
      python_env: py313

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.10.0

      - name: Install dev dependencies
        run: |
          set -vxeuo pipefail
          pixi install --environment=${{ env.python_env }}
          pixi list --environment=${{ env.python_env }}
          pixi run --environment=${{ env.python_env }} pip list
          pixi run --environment=${{ env.python_env }} conda list

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          pixi run --environment=${{ env.python_env }} python -m build

      - name: Check for packaging errors
        run: pixi run --environment=${{ env.python_env }} twine check --strict dist/*

      - name: Install produced wheel
        run: pixi run --environment=${{ env.python_env }} pip install dist/*.whl

      - name: Test module is importable using the installed wheel
        # If more than one module in src/ replace with module name to test
        run: pixi run --environment=${{ env.python_env }} python -c "import $(ls --hide='*.egg-info' src | head -1)"

      - name: Publish to PyPI using trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: false
